---
## Docker
- name: Install Podman
  become: true
  tags:
    - setup
    - podman
  dnf:
    name:
      - podman
      - pdoman-compose
    state: present

# - name: Ensure docker group exists
#   become: true
#   group:
#     name: docker
#     state: present

# - name: Adding {{ user }} to group docker
#   become: true
#   user:
#     name: "{{ user }}"
#     groups:
#       - docker
#     append: true
