---
## Pantheon Desktop
- name: Install Pantheon Desktop
  become: true
  tags:
    - setup
    - pantheon
  dnf:
    name:
      - pantheon-session-settings
      - pantheon-session-settings-overrides
      - elementary-calculator
      - elementary-calendar
      - elementary-dpms-helper
      - elementary-files
      - elementary-greeter
      - elementary-icon-theme
      - elementary-music
      - elementary-photos
      - elementary-print
      - elementary-screenshot-tool
      - elementary-shortcut-overlay
      - elementary-sound-theme
      - elementary-terminal
      - elementary-theme
      - elementary-theme-gtk2
      - elementary-theme-gtk3
      - elementary-theme-plank
      - elementary-tweaks
      - elementary-videos
      - elementary-wallpapers
      - elementary-wallpapers-gnome
      - switchboard
      - switchboard-plug-datetime
      - switchboard-plug-locale
      - switchboard-plug-power
      - switchboard-plug-security-privacy
      - switchboard-plug-useraccounts
      - lightdm
      - light-locker
      - harvey
      - monitor
    state: present

- name: Configure - Elementary GTK Theme
  become: true
  tags:
    - setup
    - pantheon
    - skip_ansible_lint
  command: gsettings set org.gnome.desktop.interface gtk-theme elementary

- name: Configure - Elementary Icon Theme
  become: true
  tags:
    - setup
    - pantheon
    - skip_ansible_lint
  command: gsettings set org.gnome.desktop.interface icon-theme elementary
