# .gitlab-ci.yml

image: "fedora:30"

before_script:
  - dnf update --refresh -y && dnf install git ansible -y

home:
  script:
    - ansible-playbook -K ./setup.yml --tags setup,home,cleanup
  
# work:
#   script:
#     - ansible-playbook -K ./setup.yml --tags setup,work