## Repositories
- name: Enable AMZ / Extras Repo
  become: true
  tags:
    - setup
    - repos
    - repos-extras
  yum_repository:
    name: fedora-extensions-extras
    description: 'Fedora Extensions $releasever - $basearch - Extras'
    baseurl: https://copr-be.cloud.fedoraproject.org/results/amz/extras/fedora-$releasever-$basearch/
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/amz/extras/pubkey.gpg
    gpgcheck: false
    enabled: true

- name: Enable Decathorpe / Pantheon Staging Repo
  become: true
  tags:
    - setup
    - repos
    - repos-pantheon
  yum_repository:
    name: fedora-extensions-pantheon
    description: 'Fedora Extensions $releasever - $basearch - Pantheon'
    baseurl: https://copr-be.cloud.fedoraproject.org/results/decathorpe/elementary-staging/fedora-$releasever-$basearch/
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/decathorpe/elementary-staging/pubkey.gpg
    gpgcheck: true
    enabled: true

- name: Enable Decathorpe / Appcenter Repo
  become: true
  tags:
    - setup
    - repos
    - repos-appcenter
  yum_repository:
    name: fedora-extensions-appcenter
    description: 'Fedora Extensions $releasever - $basearch - Appcenter'
    baseurl: https://copr-be.cloud.fedoraproject.org/results/decathorpe/elementary-appcenter/fedora-$releasever-$basearch/
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/decathorpe/elementary-appcenter/pubkey.gpg
    gpgcheck: true
    enabled: true

- name: Enable Negativo17 / Multimedia Repo
  become: true
  tags:
    - setup
    - repos
    - repos-multimedia
  yum_repository:
    name: fedora-extensions-multimedia
    description: 'Fedora Extensions $releasever - $basearch - Multimedia'
    baseurl: https://negativo17.org/repos/multimedia/fedora-$releasever/$basearch/
    gpgkey: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
    gpgcheck: true
    enabled: true

- name: Enable Remi's PHP Repo
  become: true
  tags:
    - setup
    - repos
    - repos-remi
    - repos-php
  yum_repository:
    name: fedora-extensions-php
    description: 'Fedora Extensions $releasever - $basearch - PHP'
    baseurl: https://rpms.remirepo.net/fedora/$releasever/remi/$basearch/
    gpgkey: https://rpms.remirepo.net/RPM-GPG-KEY-remi-$releasever
    gpgcheck: true
    enabled: true

- name: Enable Microsoft / Visual Studio Code Repo
  become: true
  tags:
    - setup
    - repos
    - repos-vscode
  yum_repository:
    name: fedora-extensions-vscode
    description: 'Fedora Extensions $releasever - $basearch - Visual Studio Code'
    baseurl: https://packages.microsoft.com/yumrepos/vscode/
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: true
    enabled: true

- name: Enable Microsoft / .Net Core Repo
  become: true
  tags:
    - setup
    - repos
    - repos-dotnetcore
  yum_repository:
    name: fedora-extensions-dotnet
    description: 'edora Extensions $releasever - $basearch - .NET Core'
    baseurl: https://packages.microsoft.com/fedora/30/prod/
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: true
    enabled: true

## Update All
- name: Update All
  become: true
  tags:
    - setup
    - skip_ansible_lint
  dnf:
    name: "*"
    state: latest

## Additional Libraries / Apps (Recommended)
- name: Install Additional Libraries / Packages
  become: true
  tags:
    - setup
    - libs
  dnf:
    name:
      # cli editor
      - nano
      # shell
      - zsh
      - antibody
      - util-linux-user
      # codecs 
      - gstreamer1-plugins-bad
      - gstreamer1-plugins-good
      - gstreamer1-plugins-base
      - gstreamer1-plugins-ugly
      - gstreamer1-plugins-fc
      - ffmpeg
      - mpg123
      - x264
      # compression libs
      - rar
      - p7zip
      # iphone support
      - ifuse
      - libplist
      - libplist-python
      - libimobiledevice
      - libimobiledevice-utils
      - libimobiledevice-devel
      - usbmuxd
      # other
      - screenfetch
      - dconf-editor

## Apps
- name: Install Apps
  become: true
  tags:
    - setup
    - apps
  dnf:
    name:
      - code
      - tilix
      - gnome-boxes
      - gimp
      - filezilla
    state: present

## ZSH & Antibody Setup
- name: Setup ZSH
  tags:
    - setup
    - zsh
  become: true
  become_user: root
  command: chsh -s /bin/zsh "{{ ansible_user_id }}"
  # @todo / temporary workaround
  when: ansible_os_family == "Fedora"

- name: Setup ZSH Directory
  tags:
    - setup
    - zsh
  become: true
  become_user: "{{ ansible_user_id }}"
  file:
    path: ~/.zsh
    state: directory

- name: Setup VSCode User Configuration Directory
  tags:
    - setup
    - zsh
    - code
  become: true
  become_user: "{{ ansible_user_id }}"
  file:
    path: ~/.config/Code/User
    state: directory

- name: Setup Antibody & Dotfiles
  tags:
    - setup
    - zsh
  become: true
  become_user: "{{ ansible_user_id }}"
  command: "{{ lookup('env', 'PWD') }}/install"
  # @todo / temporary workaround
  when: ansible_os_family == "Fedora"

## Pantheon Desktop
- name: Install Pantheon Desktop
  become: true
  tags:
    - setup
    - pantheon
  dnf:
    name:
      # pantheon
      - pantheon-session-settings
      - pantheon-session-settings-overrides
      - elementary-calculator
      - elementary-calendar
      - elementary-dpms-helper
      - elementary-files
      - elementary-greeter
      - elementary-icon-theme
      - elementary-music
      - elementary-photos
      - elementary-print
      - elementary-screenshot-tool
      - elementary-shortcut-overlay
      - elementary-sound-theme
      - elementary-terminal
      - elementary-theme
      - elementary-theme-gtk2
      - elementary-theme-gtk3
      - elementary-theme-plank
      - elementary-tweaks
      - elementary-videos
      - elementary-wallpapers
      - elementary-wallpapers-gnome
      - switchboard
      - switchboard-plug-datetime
      - switchboard-plug-locale
      - switchboard-plug-power
      - switchboard-plug-security-privacy
      - switchboard-plug-useraccounts
      # other
      - lightdm
      - light-locker
      - harvey
      - monitor
    state: present

- name: Configure - Elementary GTK Theme
  become: true
  tags:
    - setup
    - pantheon
  command: gsettings set org.gnome.desktop.interface gtk-theme elementary
  # @todo / temporary workaround
  when: ansible_os_family == "Fedora"

- name: Configure - Elementary Icon Theme
  become: true
  tags:
    - setup
    - pantheon
  command: gsettings set org.gnome.desktop.interface icon-theme elementary
  # @todo / temporary workaround
  when: ansible_os_family == "Fedora"


## Development Tools
- name: Install Development Tools & Libraries
  become: true
  tags:
    - setup
    - development
  dnf:
    name:
      # Development Tools & Libraries
      - "@Development Tools"
      - "@C Development Tools and Libraries"
      # Fedora RPM
      - fedora-packager
      - rpmdevtools
      # Docker 
      - docker
      - docker-compose
      # C / GTK / Vala
      - meson
      - granite-devel
      - switchboard-devel
      - GConf2-devel
      - polkit-devel
      # Python
      - python
      - python3-pip
      # PHP Latest (v7.3)
      - php
      - php-common
      - php-devel
      - php-opcache
      - php-mcrypt
      - php-cli
      - php-gd
      - php-curl
      - php-fpm
      - php-gmp
      - php-curl
      - php-intl
      - php-mbstring
      - php-mysqlnd
      - php-xmlrpc
      - php-bcmath
      - php-xml
      - php-zip
      - php-imap
      - php-posix
      - php-xdebug
      - php-xml
      - composer
      # PHP Stable (v7.1)
      - php71
      - php71-php-common
      - php71-php-devel
      - php71-php-opcache
      - php71-php-mcrypt
      - php71-php-cli
      - php71-php-gd
      - php71-php-curl
      - php71-php-fpm
      - php71-php-gmp
      - php71-php-curl
      - php71-php-intl
      - php71-php-mbstring
      - php71-php-mysqlnd
      - php71-php-xmlrpc
      - php71-php-bcmath
      - php71-php-xml
      - php71-php-zip
      - php71-php-imap
      - php71-php-posix
      - php71-php-xdebug
      - php71-php-xml
      # Java (v8)
      - java-1.8.0-openjdk
      - java-1.8.0-openjdk-devel
      - java-1.8.0-openjdk-headless
      # C# / .NET Core 3
      - dotnet-sdk-3.0

##  Virtualization
- name: Install Virtualization Tools & Libraries
  become: true
  tags:
    - setup
    - virt
  dnf:
    name:
      # QEMU
      - qemu
      - qemu-img

## Development Config - Visual Studio Code
# - name: Development Setup - Configure - Visual Studio Code - Extensions
#   become_user: "{{ ansible_user_id }}"
#   tags:
#     - setup
#     - development
#     - vscode
#   command: "code --install-extension {{ item }}"
#   with_items:
#     # file support
#     - "asabil.meson"
#     - "redhat.vscode-yaml"
#     - "laurenttreguier.rpm-spec"        
#     - "thiagoabreu.vala"
#     # mjml
#     - "attilabuti.vscode-mjml"
#     # theme
#     - "nonylene.dark-molokai-theme"
#     # linting
#     - "davidanson.vscode-markdownlint"
#     - "ms-vscode.vscode-typescript-tslint-plugin"
#     # c#
#     - "ms-vscode.csharp"
#     - "jchannon.csharpextensions"

## Drivers
- name: Install AMD X11 Driver
  become: true
  tags:
    - amd
  dnf:
    name: xorg-x11-drv-amdgpu
    state: present

- name: Install Intel X11 Driver
  become: true
  tags:
    - intel
  dnf:
    name: xorg-x11-drv-intel
    state: present

- name: Install Mesa Drivers (32bit)
  become: true
  tags:
    - setup
    - intel
    - amd
  dnf:
    name:
      - mesa-dri-drivers.i686
      - mesa-libGL.i686
    state: present

## Games / Steam
- name: Install Steam
  become: true
  tags:
    - games
    - amd
  dnf:
    name: steam
    state: present

## Cleanup - XFCE
- name: Cleanup - XFCE
  become: true
  tags:
    - cleanup
  dnf:
    name:
      - abiword
      - albatross-gtk2-theme
      - albatross-gtk3-theme
      - arc-theme
      - arc-theme-plank
      - asunder
      - catfish
      - claws-mail
      - claws-mail-plugins-archive
      - claws-mail-plugins-att-remover
      - claws-mail-plugins-attachwarner
      - claws-mail-plugins-fetchinfo
      - claws-mail-plugins-mailmbox
      - claws-mail-plugins-newmail
      - claws-mail-plugins-notification
      - claws-mail-plugins-pgp
      - claws-mail-plugins-rssyl
      - claws-mail-plugins-smime
      - claws-mail-plugins-spam-report
      - claws-mail-plugins-tnef
      - claws-mail-plugins-vcalendar
      - dnfdragora
      - dnfdragora-updater
      - fedora-release-notes
      - firewall-config
      - galculator
      - geany
      - gparted
      - greybird-xfce4-notifyd-theme
      - gtk-xfce-engine
      - gnumeric
      - im-chooser-xfce
      - libselinux-utils
      - libxfce4ui
      - libxfce4util
      - mousepad
      - pidgin
      - seahorse
      - system-config-keyboard
      - system-config-keyboard-base
      - system-config-language
      - system-config-users
      - system-config-printer
      - tint2
      - pavucontrol
      - xarchiver
      - xfce-polkit
      - xfce4-about
      - xfce4-appfinder
      - xfce4-battery-plugin
      - xfce4-clipman-plugin
      - xfce4-datetime-plugin
      - xfce4-dict
      - xfce4-dict-plugin
      - xfce4-diskperf-plugin
      - xfce4-eyes-plugin
      - xfce4-fsguard-plugin
      - xfce4-genmom-plugin
      - xfce4-mailwatch-plugin
      - xfce4-mount-plugin
      - xfce4-netload-plugin
      - xfce4-notifyd
      - xfce4-panel
      - xfce4-places-plugin
      - xfce4-pulseaudio-plugin
      - xfce4-screenshooter
      - xfce4-screenshooter-plugin
      - xfce4-session
      - xfce4-session-engines
      - xfce4-settings
      - xfce4-systemload-plugin
      - xfce4-taskmanager
      - xfce4-terminal
      - xfce4-time-out-plugin
      - xfce4-verve-plugin
      - xfce4-weather-plugin
      - xfce4-whiskermenu-plugin
      - xfce4-xkb-plugin
      - xscreensaver
      - xscreensaver-base
      - xscreensaver-extras
      - xscreensaver-extras-base
    state: absent

## Cleanup - GNOME
- name: Cleanup - GNOME
  become: true
  tags:
    - cleanup
  dnf:
    name:
      - cheese
      - nautilus
      - totem
      - rhythmbox
      - gdm
      - gnome-abrt
      - gnome-system-monitor
      - gnome-terminal
      - gnome-photos
      - gnome-weather
      - gnome-calendar
      - gnome-screenshot
      - gnome-calculator
      - gnome-clocks
      - gnome-maps
    state: absent

## Cleanup - Other
- name: Cleanup - Other
  become: true
  tags:
    - cleanup
  dnf:
    name:
      - abrt
      - abrt-addon-ccpp
      - abrt-addon-coredump-helper
      - abrt-addon-kerneloops
      - abrt-addon-pstoreoops
      - abrt-addon-vmcore
      - abrt-addon-xorg
      - abrt-cli
      - abrt-dbus
      - abrt-gui-libs
      - abrt-libs
      - abrt-plugin-bodhi
      - abrt-retrace-client
      - abrt-tui
      - transmission
      - transmission-common
      - transmission-gtk
    state: absent