---
- include: repositories.yml
- include: packages.yml
- include: user.yml
- include: development.yml
- include: docker.yml
#- include: flatpak.yml
#- include: mssql-server.yml
#- include: php.yml
#- include: cleanup.yml
