- name: Pantheon | Install Desktop
  become: true
  dnf:
    name: '{{ pantheon_desktop }}'
    state: present

- name: Pantheon | Install LightDM
  become: true
  dnf:
    name: '{{ pantheon_lightdm }}'
