---
## Snap
- name: SNAP | install snapd
  become: true
  dnf:
    name: snapd

- name: SNAP | enable snapd service
  become: true
  service:
    name: snapd
    enabled: true
    state: started

- name: SNAP | install snap apps
  become: true
  snap:
    name: '{{ snaps }}'
    state: present