---
# ZSH Setup
# - name: User | install zsh, antibody & utilities
#   become: true
#   dnf:
#     name: '{{ user_packages }}'
#     state: present

# - name: User | setup user account
#   become: true
#   user:
#     name: '{{ user }}'
#     comment: '{{ username }}'
#     shell: /bin/zsh
#     groups:
#       - wheel

- name: Dotfiles | Setup NixOS Configuration
  tags:
    - setup
    - dotfiles
  become: true
  file:
    src: '{{ dotfiles_dir }}/src/nixos/configuration.nix'
    dest: '/etc/nixos/configuration.nix'
    state: link
    force: true

# - name: User | setup vscode user configuration directory
#   tags:
#     - setup
#     - zsh
#     - code
#   become: true
#   become_user: '{{ user }}'
#   file:
#     path: ~/.config/Code/User
#     state: directory
#     mode: 0755

- name: Dotfiles | Remove existing ~/.zshrc
  tags:
    - setup
    - zsh
  become: true
  become_user: '{{ user }}'
  file:
    path: ~/.zshrc
    state: absent

- name: Dotfiles | Create .zsh Directory
  tags:
    - setup
    - zsh
  become: true
  become_user: '{{ user }}'
  file:
    path: '/home/{{ user }}/.zsh'
    state: directory
    mode: 0755

- name: Dotfiles | Setup ZSH
  tags:
    - setup
    - zsh
  become: true
  become_user: '{{ user }}'
  file:
    src: '{{ dotfiles_dir }}/{{ item.value.src }}'
    dest: '{{ item.value.dest }}'
    state: link
    force: true
  with_dict: '{{ zsh_links }}'
  # notify: INSTALL_VSCODE_EXTENSIONS