---
- name: Converge
  hosts: all
  connection: docker
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - dotfiles_dir: "{{ lookup('env', 'PWD') | dirname | dirname | dirname }}"
  tasks:
    - name: "Include amz.setup"
      include_role:
        name: "amz.setup"
