---
- name: Converge
  hosts: all
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - user: amz
    - username: 'AMZ-X'
  roles:
    - role: repositories
    - role: packages
    - role: user
    - role: pantheon
    - role: development
    - role: docker
    - role: virtualization
    - role: selinux
    - role: cleanup
    # @todo
    # Flatpak role cannot complete successfully because of SELinux, workaround needed
    # - role: flatpak
