#!/usr/bin/env zsh

### SHELL
export SHELL=/bin/zsh

### EDITOR
export EDITOR=nano

### ALIASES
source ~/.zsh/alias

### PATHS
source ~/.zsh/paths

### PLUGINS (ZPM - ZSH Plugin Manager)
source ~/.zsh/plugins

### HOOKS
source ~/.zsh/hooks
