---
# System Configuration
- name: Install Python SELinux
  become: true
  dnf:
    name: libselinux-python3
    state: present

- name: Disable SELinux
  become: true
  selinux:
    state: disabled

- name: Set Inotify Watches
  become: true
  sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present
    reload: false
