# ~/.zshrc

# LANG
export LANG=en_US.UTF-8

# EDITOR
export EDITOR=nano

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# SSH
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Default
source /etc/profile

# Java
source ~/.zsh/java

# Android
source ~/.zsh/android

# Alias
source ~/.zsh/alias

# Theme
source ~/.zsh/theme

# Oh My ZSH
source ~/.zsh/oh-my-zsh

# Antibody (plugin manager)
antibody bundle < ~/.zsh/plugins > ~/.zsh/plugins.sh
source ~/.zsh/plugins.sh

