# ~/.zshrc

# LANG
export LANG=en_US.UTF-8

# EDITOR
export EDITOR=nano

# SSH
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Default
source /etc/profile

# Alias
source ~/.zsh/alias

# Path
source ~/.zsh/path

# Theme
source ~/.zsh/theme

# Oh My ZSH
source ~/.zsh/oh-my-zsh

# Plugins
antibody bundle < ~/.zsh/plugins > ~/.zsh/plugins.sh
source ~/.zsh/plugins.sh
