name: DotfilesCI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Setup Virtual Environment
      run: sudo apt install virtualenv -y
    - name: Install Dependencies
      run: |
        virtualenv .virtenv 
        source .virtenv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Molecule Tests
      run: |
        source .virtenv/bin/activate
        cd ${{ github.workspace }}/setup
        molecule test --destroy=never